version: '3'

services:
  mysql-development:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: merchandise-circ
    ports:
      - "3308:3306"

  # development:
  #   image: thisham/merchandise:dev
  #   ports:
  #     - "8080:8000"
  
  app:
    depends_on:
      - mysql-development
    build: .
    container_name: merchandise
    ports:
      - "19000:8000"
    env_file:
      - ./test.env
