version: '3'

services:
  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: merchandise-circ
    ports:
      - "3308:3306"

  # development:
  #   image: thisham/merchandise:dev
  #   ports:
  #     - "8080:8000"
  
  app:
    image: thisham/merchandise:latest
    ports:
      - "19000:8000"
