// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	merchandises "merchandise-circulation-api/src/app/merchandises"

	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// CheckMerchandiseExistsByUPC provides a mock function with given fields: upc
func (_m *Data) CheckMerchandiseExistsByUPC(upc string) bool {
	ret := _m.Called(upc)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(upc)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SelectAllMerchandises provides a mock function with given fields:
func (_m *Data) SelectAllMerchandises() ([]merchandises.Domain, error) {
	ret := _m.Called()

	var r0 []merchandises.Domain
	if rf, ok := ret.Get(0).(func() []merchandises.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]merchandises.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectMerchandiseByUPC provides a mock function with given fields: upc
func (_m *Data) SelectMerchandiseByUPC(upc string) (merchandises.Domain, error) {
	ret := _m.Called(upc)

	var r0 merchandises.Domain
	if rf, ok := ret.Get(0).(func(string) merchandises.Domain); ok {
		r0 = rf(upc)
	} else {
		r0 = ret.Get(0).(merchandises.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(upc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
