version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        variant: alpine3.14

    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mysql:8.0.17
    restart: unless-stopped
    volumes:
      - mysql-data:/storage/docker/mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: merchandise-circ

volumes:
  mysql-data:
