name: "running unit test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    name: "unit test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "setup go"
        uses: actions/setup-go@v2
        with: 
          go-version: 1.17.2
      - name: running unit test
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic
      - name: upload static analysis
        uses: codecov/codecov-action@v3

  docker-compose:
    name: build docker image
    runs-on: "ubuntu-latest"
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: config .env
        env:
          ENV: ${{secrets.ENV_STAGING}}
        run: echo "$ENV" > app.env
      - name: build image
        run: docker build -t thisham/merchandise-api:latest .
      - name: login docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: push image to dockerhub
        run: docker push thisham/merchandise-api:latest
    
  # deployment:
  #   name: deploy on heroku
  #   runs-on: "ubuntu-latest"
  #   needs: docker-compose
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: 

